//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BP01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load ${inputFile}, protein
        ///load ${outputFileWithoutExtension}${outputFileExtension}, result
        ///
        ///
        ///select zn, symbol ${centralAtomSymbol};
        ///select res, result around 0.01 | result;
        ///
        ///hide;
        ///show cartoon;
        ///show spheres, zn;
        ///
        ///color wheat;
        ///color green, res;
        ///color blue, zn;
        ///
        ///disable all;
        ///enable protein;
        ///
        ///zoom res;
        ///
        ///delete zn;
        ///delete res;
        ///save ${outputFileWithoutExtension}.pse;.
        /// </summary>
        internal static string script_PyMOL {
            get {
                return ResourceManager.GetString("script_PyMOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load ${inputFile}, protein
        ///load ${outputFileWithoutExtension}_step_1${outputFileExtension}, step1
        ///load ${outputFileWithoutExtension}_step_2${outputFileExtension}, step2
        ///load ${outputFileWithoutExtension}_step_3${outputFileExtension}, step3
        ///load ${outputFileWithoutExtension}_step_4${outputFileExtension}, step4
        ///load ${outputFileWithoutExtension}_step_5${outputFileExtension}, step5
        ///
        ///
        ///select zn, symbol ${centralAtomSymbol};
        ///select sel1, step1 around 0.01 | step1;
        ///select sel2, step2 around 0.01 | step2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_PyMOL_steps_m1 {
            get {
                return ResourceManager.GetString("script_PyMOL_steps_m1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load ${inputFile}, protein
        ///load ${outputFileWithoutExtension}_step_1${outputFileExtension}, step1
        ///load ${outputFileWithoutExtension}_step_2${outputFileExtension}, step2
        ///load ${outputFileWithoutExtension}_step_3${outputFileExtension}, step3
        ///load ${outputFileWithoutExtension}_step_4${outputFileExtension}, step4
        ///load ${outputFileWithoutExtension}_step_5${outputFileExtension}, step5
        ///
        ///
        ///select zn, symbol ${centralAtomSymbol};
        ///select sel1, step1 around 0.01 | step1;
        ///select sel2, step2 around 0.01 | step2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_PyMOL_steps_m2 {
            get {
                return ResourceManager.GetString("script_PyMOL_steps_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load ${inputFile}, protein
        ///load ${outputFileWithoutExtension}_step_1${outputFileExtension}, step1
        ///load ${outputFileWithoutExtension}_step_2${outputFileExtension}, step2
        ///load ${outputFileWithoutExtension}_step_3${outputFileExtension}, step3
        ///load ${outputFileWithoutExtension}_step_4${outputFileExtension}, step4
        ///load ${outputFileWithoutExtension}_step_5${outputFileExtension}, step5
        ///
        ///
        ///select zn, symbol ${centralAtomSymbol};
        ///select sel1, step1 around 0.01 | step1;
        ///select sel2, step2 around 0.01 | step2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_PyMOL_steps_m3 {
            get {
                return ResourceManager.GetString("script_PyMOL_steps_m3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load ${inputFile}, protein
        ///load ${outputFileWithoutExtension}_step_1${outputFileExtension}, step1
        ///load ${outputFileWithoutExtension}_step_2${outputFileExtension}, step2
        ///load ${outputFileWithoutExtension}_step_3${outputFileExtension}, step3
        ///load ${outputFileWithoutExtension}_step_4${outputFileExtension}, step4
        ///load ${outputFileWithoutExtension}_step_5${outputFileExtension}, step5
        ///load ${outputFileWithoutExtension}_step_6${outputFileExtension}, step6
        ///
        ///
        ///select zn, symbol ${centralAtomSymbol};
        ///select  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_PyMOL_steps_m4 {
            get {
                return ResourceManager.GetString("script_PyMOL_steps_m4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load ${inputFile}, protein
        ///load ${outputFileWithoutExtension}_step_1${outputFileExtension}, step1
        ///load ${outputFileWithoutExtension}_step_2${outputFileExtension}, step2
        ///load ${outputFileWithoutExtension}_step_3${outputFileExtension}, step3
        ///load ${outputFileWithoutExtension}_step_4${outputFileExtension}, step4
        ///load ${outputFileWithoutExtension}_step_5${outputFileExtension}, step5
        ///load ${outputFileWithoutExtension}_step_6${outputFileExtension}, step6
        ///load ${outputFileWithoutExtension}_step_7${outputFil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_PyMOL_steps_m5 {
            get {
                return ResourceManager.GetString("script_PyMOL_steps_m5", resourceCulture);
            }
        }
    }
}
